package Visual;

import Modelos.Loja;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo e Guilherme
 */
public class telaCadastro extends javax.swing.JFrame {

    // Variável para verificar se tem jInternalFrame aberto
    private TelaFornecedor verFornecedor;
    private TelaCliente verCliente;
    private TelaFuncionario verFuncionario;
    private TelaVenda verVenda;
    private TelaCadastroProduto verProduto;
    protected Loja loja;

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        loja = new Loja();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionVender = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        optCadCliente = new javax.swing.JMenuItem();
        optCadFornecedor = new javax.swing.JMenuItem();
        optCadFuncionario = new javax.swing.JMenuItem();
        optCadProduto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        optRelCompra = new javax.swing.JMenuItem();
        optRelVenda = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        optSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softwear");
        setExtendedState(6);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        optionVender.setText("Vender");
        optionVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionVenderMouseClicked(evt);
            }
        });
        optionVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionVenderActionPerformed(evt);
            }
        });
        jMenuBar1.add(optionVender);

        jMenu1.setText("Cadastro");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        optCadCliente.setText("Cliente");
        optCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(optCadCliente);

        optCadFornecedor.setText("Fornecedor");
        optCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(optCadFornecedor);

        optCadFuncionario.setText("Funcionario");
        optCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(optCadFuncionario);

        optCadProduto.setText("Produto");
        optCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCadProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(optCadProduto);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Relatórios");

        optRelCompra.setText("Compras");
        jMenu4.add(optRelCompra);

        optRelVenda.setText("Vendas");
        jMenu4.add(optRelVenda);

        jMenuBar1.add(jMenu4);

        menuAjuda.setText("Ajuda");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaActionPerformed(evt);
            }
        });

        optSair.setText("Sair");
        optSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSairActionPerformed(evt);
            }
        });
        menuAjuda.add(optSair);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void optCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCadClienteActionPerformed
        // verifica se tem algum jInternalFrame igual aberto
        if (verCliente == null) {
            verCliente = new TelaCliente(loja);
        }
// se não estiver visível ele adiciona ao jDP e torna visível
        if (!verCliente.isVisible()) {
            jDesktopPane1.add(verCliente);
            verCliente.setVisible(true);
            verCliente.setPosicao();

        }

        verCliente.toFront();

    }//GEN-LAST:event_optCadClienteActionPerformed

    private void menuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuAjudaActionPerformed

    private void optSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if (sair == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_optSairActionPerformed

    private void optCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCadFornecedorActionPerformed
        // verifica se tem algum jInternalFrame igual aberto
        if (verFornecedor == null) {
            verFornecedor = new TelaFornecedor();
        }
// se não estiver visível ele adiciona ao jDP e torna visível
        if (!verFornecedor.isVisible()) {
            jDesktopPane1.add(verFornecedor);
            verFornecedor.setVisible(true);
            verFornecedor.setPosicao();

        }

        verFornecedor.toFront();

    }//GEN-LAST:event_optCadFornecedorActionPerformed

    private void optCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCadFuncionarioActionPerformed
        // verifica se tem algum jInternalFrame igual aberto
        if (verFuncionario == null) {
            verFuncionario = new TelaFuncionario();

        }
// se não estiver visível ele adiciona ao jDP e torna visível
        if (!verFuncionario.isVisible()) {
            jDesktopPane1.add(verFuncionario);
            verFuncionario.setVisible(true);
            verFuncionario.setPosicao();

        }
        verFuncionario.toFront();
    }//GEN-LAST:event_optCadFuncionarioActionPerformed

    private void optionVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionVenderActionPerformed

    }//GEN-LAST:event_optionVenderActionPerformed

    private void optionVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionVenderMouseClicked
        // verifica se tem algum jInternalFrame igual aberto
        if (verVenda == null) {
            verVenda = new TelaVenda(loja);
        }
        // se não estiver visível ele adiciona ao jDP e torna visível
        if (!verVenda.isVisible()) {
            jDesktopPane1.add(verVenda);
            verVenda.setVisible(true);
            verVenda.setPosicao();

        }
        verVenda.toFront();

    }//GEN-LAST:event_optionVenderMouseClicked

    private void optCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCadProdutoActionPerformed

// verifica se tem algum jInternalFrame igual aberto
        if (verProduto == null) {
            verProduto = new TelaCadastroProduto(loja);
        }
// se não estiver visível ele adiciona ao jDP e torna visível
        if (!verProduto.isVisible()) {
            jDesktopPane1.add(verProduto);
            verProduto.setVisible(true);
            verProduto.setPosicao();

        }

        verProduto.toFront();


    }//GEN-LAST:event_optCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem optCadCliente;
    private javax.swing.JMenuItem optCadFornecedor;
    private javax.swing.JMenuItem optCadFuncionario;
    private javax.swing.JMenuItem optCadProduto;
    private javax.swing.JMenuItem optRelCompra;
    private javax.swing.JMenuItem optRelVenda;
    private javax.swing.JMenuItem optSair;
    private javax.swing.JMenu optionVender;
    // End of variables declaration//GEN-END:variables
}
